qc:
  build: .
  dockerfile: Dockerfile
  volumes:
    - .:/src
  ports:
    - "2300:8080"
  environment:
    VIRTUAL_HOST: buying.namdv.net
    VIRTUAL_PORT: 8080
  links:
    - mysql
  command: nodemon -L server/app/start.js
mysql:
  image: namshi/mysql
  ports:
      - "3306:3306"
  environment:
    user: root
    password: root
  volumes:
    - ~/local/namshi/mysql:/var/lib/mysql
